# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-22 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eating',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
