# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-22 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0003_auto_20190422_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eating',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Eating',
        ),
    ]
