# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-22 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calorimetr', '0004_auto_20190422_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calorie_num', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
