# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-22 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0006_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Eating',
        ),
    ]
