# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0008_auto_20190504_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('calorie', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
    ]
