# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0009_eat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='portion',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='protein',
        ),
    ]
