# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0011_auto_20190504_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eat',
        ),
        migrations.AddField(
            model_name='dish',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
