# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0012_auto_20190504_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='eating',
        ),
    ]
