# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0013_remove_dish_eating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='eating',
            field=models.ManyToManyField(to='calorimetr.Eating'),
        ),
    ]
