# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 20:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0014_dish_eating'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)])),
                ('activity', models.CharField(choices=[('Min', 'Minimal activity'), ('W', 'Week activity'), ('Med', 'Medium activity'), ('H', 'High activity'), ('E', 'Extraactivity')], max_length=3)),
                ('sex', models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1)),
                ('diet', models.CharField(choices=[('L', 'Loose weight level'), ('K', 'Keep weight level'), ('I', 'Increase weight level')], max_length=1)),
            ],
        ),
    ]
