# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 21:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorimetr', '0015_user_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)])),
                ('activity', models.CharField(choices=[('Min', 'Minimal activity'), ('W', 'Week activity'), ('Med', 'Medium activity'), ('H', 'High activity'), ('E', 'Extraactivity')], max_length=3)),
                ('sex', models.CharField(choices=[('W', 'Woman'), ('M', 'Man')], max_length=1)),
                ('diet', models.CharField(choices=[('L', 'Loose weight level'), ('K', 'Keep weight level'), ('I', 'Increase weight level')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_params',
        ),
    ]
