# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0017_auto_20190505_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet',
            field=models.CharField(choices=[('L', 'Потеря веса'), ('K', 'Поддержание веса'), ('I', 'Набор веса')], max_length=1),
        ),
        migrations.AddField(
            model_name='userweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorimetr.UserProfile'),
        ),
    ]
