# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorimetr', '0018_auto_20190505_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wish_weight',
            field=models.IntegerField(default=0),
        ),
    ]
